apiVersion: v1
kind: Service
metadata:
  name: ledger
  namespace: cwb
  labels:
    app: ledger
spec:
  type: ClusterIP
  selector:
    app: ledger
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
